### PR TITLE
Add support for meteor login resume tokens

### PR DESCRIPTION
**Pull request by ppettit**
If the token is not valid then it will automatically retry using
the username/email and password. this way there is no need to
check if the token is expired, although you end up making an extra
call.

Tokens are automatically saved for use when a reconnection is
required, and you can also pass an optional token into the login
method so that your app can persist it between runs.

Not sure if this is the cleanest way of doing this, but it seems to work :wink:

### CODE REVIEW

**Comment by keyvanfatehi** [comment]
Would this get rid of all the extra entries in the database under services.resume.loginTokens ?

**Comment by ppettit** [comment]
hi @keyvanfatehi,

yes, that is the reason i wrote it.

if your app gets disconnected from meteor but still running it will automatically try and reuse the previous token, so a new one will not be created.

if your token is expired or removed from the database (even while the app is connected) it will retry the login using the username and password instead (thus generating a new token).

if you want tokens to be reused between runs of your app though, you have to persist them in your app. for example, we do something like this:

```python
def on_connected(self):
    logger.info('Connected to Meteor')
    user = conf.get('ddp', 'user')
    password = conf.get('ddp', 'password')
    token = conf.get('ddp', 'token')
    self.client.login(user, password, token=token)

def on_logged_in(self, data):
    conf.set('ddp', 'token', data['token'])
    conf.update()

meteor = conf.get('ddp', 'meteor')
client = MeteorClient(meteor)
client.on('connected', on_connected)
client.on('logged_in', on_logged_in)
client.connect()

# do stuff!
```
where `conf` is a simple class to read/write from an ini file.

we found that in our app (where we have 50+ devices all logging in with the same credentials) that `services.resume.loginTokens` got huge pretty quickly (especially during testing) and that started slowing logins down. this fixed that for us.

thanks,

paul.

**Comment by keyvanfatehi** [comment]
@ppettit thanks the detailed answer and the code!
@hharnisc is there any reasons why this isn't merged upstream? just busy?

I'll be trying this and will report if i have any bugs.

**Comment by ppettit** [comment]
@keyvanfatehi no problem! please do let me know how you get on with it - i am happy to look at any issues you find.

**Comment by hharnisc** [comment]
@keyvanfatehi yep haven't had the cycles to test this and merge it in. Have some time planned for tomorrow to do so. Thanks for being patient.

**Comment by keyvanfatehi** [comment]
Ok cool. FWIW I have merged this and started using it without issues.

**Pull request merged**
